server:
  port: ${port:8001}

spring:
  application:
    name: cscloud-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.11:8848
        namespace: 203f95ec-6871-4138-9199-5b079c6c1e3f

logging:
  level:
    root: info
    org.springframeWork: info